/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package anagrams;

import anagrams.model.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.io.*;

public class DictionaryTests {
    @Test public void dictHasCorrectFiles() {
        try{
			Dictionary testDict = new Dictionary();
			assertNotNull(testDict);
		}
		catch(Exception e){
			System.out.println("Ooops. Wrong files");
		}
    }

    
    @Test public void checkScoreThree(){
		try{
			Dictionary testDict = new Dictionary();
			assertEquals(testDict.checkWord("TWO"), 400);
		}
		catch(Exception e){
			System.out.println("Ooops. Wrong files");
		}
	}
    
    @Test public void checkScoreFour(){
		try{
			Dictionary testDict = new Dictionary();
			assertEquals(testDict.checkWord("MARK"), 800);
		}
		catch(Exception e){
			System.out.println("Ooops. Wrong files");
		}
	}
	
    @Test public void checkScoreFive(){
		try{
			Dictionary testDict = new Dictionary();
			assertEquals(testDict.checkWord("GUESS"), 1200);
		}
		catch(Exception e){
			System.out.println("Ooops. Wrong files");
		}
	}
	
	    
    @Test public void checkScoreSix(){
		try{
			Dictionary testDict = new Dictionary();
			assertEquals(testDict.checkWord("SPARKS"), 2000);
		}
		catch(Exception e){
			System.out.println("Ooops. Wrong files");
		}
	}
}
